apiVersion: v1
kind: Template
labels:
  template: manageiq-ext-db
metadata:
  name: manageiq-ext-db
  annotations:
    description: "ManageIQ appliance with persistent storage using a external DB host"
    tags: "instant-app,manageiq,miq"
    iconClass: "icon-rails"
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: miq-anyuid
- apiVersion: v1
  kind: Secret
  metadata:
    name: "${NAME}-secrets"
  stringData:
    pg-password: "${DATABASE_PASSWORD}"
    database-url: "postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_SERVICE_NAME}:${DATABASE_PORT}/${DATABASE_NAME}?encoding=utf8&pool=5&wait_timeout=5"
    v2-key: "${V2_KEY}"
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: "Exposes and load balances ManageIQ pods"
      service.alpha.openshift.io/dependencies: '[{"name":"${DATABASE_SERVICE_NAME}","namespace":"","kind":"Service"},{"name":"${MEMCACHED_SERVICE_NAME}","namespace":"","kind":"Service"}]'
    name: ${NAME}
  spec:
    clusterIP: None
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
    selector:
      name: ${NAME}
- apiVersion: v1
  kind: Route
  metadata:
    name: ${NAME}
  spec:
    host: ${APPLICATION_DOMAIN}
    port:
      targetPort: https
    tls:
      termination: passthrough
    to:
      kind: Service
      name: ${NAME}
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: miq-app
    annotations:
      description: "Keeps track of the ManageIQ image changes"
  spec:
    dockerImageRepository: "${APPLICATION_IMG_NAME}"
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: memcached
    annotations:
      description: "Keeps track of the Memcached image changes"
  spec:
    dockerImageRepository: "${MEMCACHED_IMG_NAME}"
- apiVersion: v1
  kind: "DeploymentConfig"
  metadata:
    name: ${NAME}
    annotations:
      description: "Defines how to deploy the ManageIQ appliance"
  spec:
    serviceName: "${NAME}"
    replicas: "${APPLICATION_REPLICA_COUNT}"
    template:
      metadata:
        labels:
          name: ${NAME}
        name: ${NAME}
      spec:
        containers:
        - name: manageiq
          image: "${APPLICATION_IMG_NAME}:${APPLICATION_IMG_TAG}"
          livenessProbe:
            tcpSocket:
              port: 443
            initialDelaySeconds: 480
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: 443
              scheme: HTTPS
            initialDelaySeconds: 200
            timeoutSeconds: 3
          ports:
          - containerPort: 80
            protocol: TCP
          - containerPort: 443
            protocol: TCP
          env:
            -
              name: "APPLICATION_INIT_DELAY"
              value: "${APPLICATION_INIT_DELAY}"
            -
              name: "GUID"
              value: "${GUID}"
            -
              name: "DATABASE_SERVICE_NAME"
              value: "${DATABASE_SERVICE_NAME}"
            -
              name: "DATABASE_REGION"
              value: "${DATABASE_REGION}"
            -
              name: "DATABASE_URL"
              valueFrom:
                secretKeyRef:
                  name: "${NAME}-secrets"
                  key: "database-url"
            -
              name: "MEMCACHED_SERVER"
              value: "${MEMCACHED_SERVICE_NAME}:11211"
            -
              name: "MEMCACHED_SERVICE_NAME"
              value: "${MEMCACHED_SERVICE_NAME}"
            -
              name: "V2_KEY"
              valueFrom:
                secretKeyRef:
                  name: "${NAME}-secrets"
                  key: "v2-key"
          resources:
            requests:
              memory: "${APPLICATION_MEM_REQ}"
              cpu: "${APPLICATION_CPU_REQ}"
            limits:
              memory: "${APPLICATION_MEM_LIMIT}"
        serviceAccount: miq-anyuid
        serviceAccountName: miq-anyuid
        terminationGracePeriodSeconds: 90
- apiVersion: v1
  kind: "Service"
  metadata:
    name: "${MEMCACHED_SERVICE_NAME}"
    annotations:
      description: "Exposes the memcached server"
  spec:
    ports:
      -
        name: "memcached"
        port: 11211
        targetPort: 11211
    selector:
      name: "${MEMCACHED_SERVICE_NAME}"
- apiVersion: v1
  kind: "DeploymentConfig"
  metadata:
    name: "${MEMCACHED_SERVICE_NAME}"
    annotations:
      description: "Defines how to deploy memcached"
  spec:
    strategy:
      type: "Recreate"
    triggers:
      -
        type: "ImageChange"
        imageChangeParams:
          automatic: true
          containerNames:
            - "memcached"
          from:
            kind: "ImageStreamTag"
            name: "memcached:${MEMCACHED_IMG_TAG}"
      -
        type: "ConfigChange"
    replicas: 1
    selector:
      name: "${MEMCACHED_SERVICE_NAME}"
    template:
      metadata:
        name: "${MEMCACHED_SERVICE_NAME}"
        labels:
          name: "${MEMCACHED_SERVICE_NAME}"
      spec:
        volumes: []
        containers:
          -
            name: "memcached"
            image: "${MEMCACHED_IMG_NAME}:${MEMCACHED_IMG_TAG}"
            ports:
              -
                containerPort: 11211
            readinessProbe:
              timeoutSeconds: 1
              initialDelaySeconds: 5
              tcpSocket:
                port: 11211
            livenessProbe:
              timeoutSeconds: 1
              initialDelaySeconds: 30
              tcpSocket:
                port: 11211
            volumeMounts: []
            env:
              -
                name: "MEMCACHED_MAX_MEMORY"
                value: "${MEMCACHED_MAX_MEMORY}"
              -
                name: "MEMCACHED_MAX_CONNECTIONS"
                value: "${MEMCACHED_MAX_CONNECTIONS}"
              -
                name: "MEMCACHED_SLAB_PAGE_SIZE"
                value: "${MEMCACHED_SLAB_PAGE_SIZE}"
            resources:
              requests:
                memory: "${MEMCACHED_MEM_REQ}"
                cpu: "${MEMCACHED_CPU_REQ}"
              limits:
                memory: "${MEMCACHED_MEM_LIMIT}"
- apiVersion: v1
  kind: "Service"
  metadata:
    name: "${DATABASE_SERVICE_NAME}"
    annotations:
      description: "Remote database service"
  spec:
    ports:
      -
        name: "postgresql"
        port: 5432
        targetPort: ${{DATABASE_PORT}}
    selector: {}
- apiVersion: v1
  kind: "Endpoints"
  metadata:
    name: "${DATABASE_SERVICE_NAME}"
  subsets:
    -
      addresses:
        -
          ip: "${DATABASE_IP}"
      ports:
        -
          port: ${{DATABASE_PORT}}
          name: "postgresql"
parameters:
  -
    name: "NAME"
    displayName: Name
    required: true
    description: "The name assigned to all of the frontend objects defined in this template."
    value: manageiq
  -
    name: "GUID"
    displayName: "ManageIQ Application GUID"
    required: true
    description: "The global identifier string for this ManageIQ application"
    from: "[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}"
    generate: expression
  -
    name: "V2_KEY"
    displayName: "ManageIQ Encryption Key"
    required: true
    description: "Encryption Key for ManageIQ Passwords"
    from: "[a-zA-Z0-9]{43}"
    generate: expression
  -
    name: "DATABASE_SERVICE_NAME"
    displayName: "PostgreSQL Service Name"
    required: true
    description: "The name of the OpenShift Service exposed for the PostgreSQL container."
    value: "postgresql"
  -
    name: "DATABASE_USER"
    displayName: "PostgreSQL User"
    required: true
    description: "PostgreSQL user that will access the database."
    value: "root"
  -
    name: "DATABASE_PASSWORD"
    displayName: "PostgreSQL Password"
    required: true
    description: "Password for the PostgreSQL user."
    from: "[a-zA-Z0-9]{8}"
    generate: expression
  -
    name: "DATABASE_IP"
    displayName: "PostgreSQL Server IP"
    required: true
    description: "PostgreSQL external server IP used to configure service."
    value: ""
  -
    name: "DATABASE_PORT"
    displayName: "PostgreSQL Server Port"
    required: true
    description: "PostgreSQL external server port used to configure service."
    value: "5432"
  -
    name: "DATABASE_NAME"
    required: true
    displayName: "PostgreSQL Database Name"
    description: "Name of the PostgreSQL database accessed."
    value: "vmdb_production"
  -
    name: "DATABASE_REGION"
    required: true
    displayName: "Application Database Region"
    description: "Database region that will be used for application."
    value: "0"
  -
    name: "MEMCACHED_SERVICE_NAME"
    required: true
    displayName: "Memcached Service Name"
    description: "The name of the OpenShift Service exposed for the Memcached container."
    value: "memcached"
  -
    name: "MEMCACHED_MAX_MEMORY"
    displayName: "Memcached Max Memory"
    description: "Memcached maximum memory for memcached object storage in MB."
    value: "64"
  -
    name: "MEMCACHED_MAX_CONNECTIONS"
    displayName: "Memcached Max Connections"
    description: "Memcached maximum number of connections allowed."
    value: "1024"
  -
    name: "MEMCACHED_SLAB_PAGE_SIZE"
    displayName: "Memcached Slab Page Size"
    description: "Memcached size of each slab page."
    value: "1m"
  -
    name: "APPLICATION_CPU_REQ"
    displayName: "Application Min CPU Requested"
    required: true
    description: "Minimum amount of CPU time the Application container will need (expressed in millicores)."
    value: "1000m"
  -
    name: "MEMCACHED_CPU_REQ"
    displayName: "Memcached Min CPU Requested"
    required: true
    description: "Minimum amount of CPU time the Memcached container will need (expressed in millicores)."
    value: "200m"
  -
    name: "APPLICATION_MEM_REQ"
    displayName: "Application Min RAM Requested"
    required: true
    description: "Minimum amount of memory the Application container will need."
    value: "6144Mi"
  -
    name: "MEMCACHED_MEM_REQ"
    displayName: "Memcached Min RAM Requested"
    required: true
    description: "Minimum amount of memory the Memcached container will need."
    value: "64Mi"
  -
    name: "APPLICATION_MEM_LIMIT"
    displayName: "Application Max RAM Limit"
    required: true
    description: "Maximum amount of memory the Application container can consume."
    value: "16384Mi"
  -
    name: "MEMCACHED_MEM_LIMIT"
    displayName: "Memcached Max RAM Limit"
    required: true
    description: "Maximum amount of memory the Memcached container can consume."
    value: "256Mi"
  -
    name: "MEMCACHED_IMG_NAME"
    displayName: "Memcached Image Name"
    description: "This is the Memcached image name requested to deploy."
    value: "docker.io/manageiq/memcached"
  -
    name: "MEMCACHED_IMG_TAG"
    displayName: "Memcached Image Tag"
    description: "This is the Memcached image tag/version requested to deploy."
    value: "latest"
  -
    name: "APPLICATION_IMG_NAME"
    displayName: "Application Image Name"
    description: "This is the Application image name requested to deploy."
    value: "docker.io/manageiq/manageiq-pods"
  -
    name: "APPLICATION_IMG_TAG"
    displayName: "Application Image Tag"
    description: "This is the Application image tag/version requested to deploy."
    value: "app-latest"
  -
    name: "APPLICATION_DOMAIN"
    displayName: "Application Hostname"
    description: "The exposed hostname that will route to the application service, if left blank a value will be defaulted."
    value: ""
  -
    name: "APPLICATION_REPLICA_COUNT"
    displayName: "Application Replica Count"
    description: "This is the number of Application replicas requested to deploy."
    value: "1"
  -
    name: "APPLICATION_INIT_DELAY"
    displayName: "Application Init Delay"
    required: true
    description: "Delay in seconds before we attempt to initialize the application."
    value: "15"
  -
    name: "APPLICATION_VOLUME_CAPACITY"
    displayName: "Application Volume Capacity"
    required: true
    description: "Volume space available for application data."
    value: "5Gi"
